version: '3.8'

services:
  nexus-console:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
    volumes:
      - ./workspace:/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Optional: for container access
    security_opt:
      - seccomp:unconfined  # Required for PTY
    cap_add:
      - SYS_PTRACE  # For debugging support
    restart: unless-stopped
    
  # Optional: Development database for session persistence
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: